### ISSUE TITLE
Cannot exactly replicate communication patterns

### ISSUE THREAD

**Issue by carsonwoods** [CUP-ECS/irregular-benchmarking#6]
`L7_Setup()` is being called once per benchmark sample. By default the benchmark runs multiple sample (and subsequently calls L7_Setup once per sample), however it should be possible to reconstruct the mesh (introduce new irregularity) within a benchmark sample. 

Currently the benchmark flow is:
- Pack up a bunch of data
- Start a loop for "irregular samples" (the `-I` flag in the benchmark launch command)
  - Call `L7_Setup()` with the parameters which defines how the data should be communicated and store in NEW database
  - Start a loop for "communication iterations" (the `-i` flag i the benchmark launch command)
    - Call `L7_Update()` every loop iteration
    - Collect communication performance data
   - Print `L7_Update()` performance metrics

When looking at CLAMR to better understand how we might identically replicate a communication pattern, I realized that I accidentally created a fairly good model for what CLAMR is actually doing. There are a few problems with this right now though. 
- [x] CLAMR has multiple databases simultaneously, whereas our benchmark only has 1
  - I'm not sure what that second database in CLAMR does. Perhaps it doesn't matter and we can just consider it *more communication*, but I'd like to be sure of that.
- [x] Currently the benchmark creates a new L7 database every sample. This should be changed to use the same database, just reinitialized. 
  - This might not be necessary, but it is still important 
- [ ] In addition to displaying the communication performance across samples, there should be a cross-sample average line which displays all the information gathered across all samples. 
- [ ] There needs to be a mechanism to read a communication pattern from a file and recreate it exactly. 
  - There will need to be an abstraction in the file structure that will allow a similar recreation of non-L7 based applications.

**Comment by carsonwoods** [comment]
On further consideration, I don't think the different databases actually matters. Since we're just sending random data, the actual location of the data shouldn't theoretically matter. 

I think that, even when reproducing a communication pattern, we still will have to sacrifice some level of communication replication because otherwise we should probably just be profiling the actual application itself. I think that a single L7 database model is a reasonable approach for now.

**Comment by carsonwoods** [comment]
Closed due to a mistake on my part with the related PR when I merged a branch prematurely. I have re-opened.

**Comment by patrickb314** [comment]
I agree we don't need to exactly replicate the communication pattern. We just want to get teh appropriate statitiscal features.
